# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

getnrofthreads <- function() {
    .Call(`_fstcore_getnrofthreads`)
}

setnrofthreads <- function(nrOfThreads) {
    .Call(`_fstcore_setnrofthreads`, nrOfThreads)
}

hasopenmp <- function() {
    .Call(`_fstcore_hasopenmp`)
}

restore_after_fork <- function(restore) {
    invisible(.Call(`_fstcore_restore_after_fork`, restore))
}

# Register entry points for exported C++ functions
methods::setLoadAction(function(ns) {
    .Call('_fstcore_RcppExport_registerCCallable', PACKAGE = 'fstcore')
})
